### ISSUE TITLE
about the number of sensor channels

### ISSUE THREAD

**Issue by gywlssww** [STRCWearlab/DeepConvLSTM_py3#7]
I study deep convolution lstm network with your paper and this repository. I'm just a starter... 
I read that the number of sensor channels is same for every feature map in all layers from your article in Sensor journal and also figure 3, which describe the architecture of the DeepConvLSTM, shows the number of channel (which D denotes) is same as D(=113).

However in the code, first conv1d layer's input shape is [batchsize(100), # of channel (113), window_length(24)] and the others
 is [batch_size(100), # of filter (64), window_length(24) ].

I understand where each number came from, but I wonder what about the consistence of # of channels? 

I checked the output tensor's shape of convolution layer but could't check the maintenance of elements of multi channels..

Thank you :)

**Comment by PellattLlo** [comment]
Apologies for a very late response. You are correct, this issue has now been fixed - channel dimensions should now be kept through all the convolutional layers.

For reference, the issue comes from pytorch Conv1D layers summing the activation of the kernels in the channel dimension, so we need to use Conv2D with a kernel size of 1 in channel dimension (i.e. kernel_size = (5,1)) to maintain the number of channels.
